[functions]
  node_bundler = "esbuild"
  directory = "netlify/functions"

[[redirects]]
  from = "/interactions"
  to = "/.netlify/functions/discord"
  status = 200
  force = true

[build]
  command = "npm run register-commands"

[build.environment]
  NODE_VERSION = "20"
